config/routes.rb
Rails.application.routes.draw do
  
  root "posts#index"
  resources :posts do
    member do
      post :tags
      delete :tag_d
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  
  post "favorites", to: "favorites#create"
  delete "favorites", to: "favorites#destroy"
  
  post "favorites_show", to: "favorites#create_show"
  delete "favorites_show", to: "favorites#destroy_show"
  resources :tags , only:[:show] do
    member do
      get :find
    end
  end
  resources :users, only:[:index, :show, :new, :create] do
    member do
      get :likes
      get :favorites
    end
  end
  
  resources :favorites, only: [:create, :destroy]#お気に入り登録/解除
  
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum:10}
    validates :email, presence: true,length: { maximum:255},
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    has_many :posts
    
    has_many :favorites,dependent: :destroy
    has_many :favorite_now, through: :favorites, source: :post
    
    def fav_in(other_post)
        self.favorites.find_or_create_by(post_id: other_post.id)
    end 
    
    def fav_out(other_post)
        favorite = self.favorites.find_by(post_id: other_post.id)
        favorite.destroy   if favorite
    end 
    
    def fav_now(other_post)
        self.favorite_now.include?(other_post)
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
  
  def likes
    @user = User.find(params[:id])
    @posts = @user.favorite_now
  end
private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/likes.html.erb
<h1><%= @user.name %>さんの詳細ページ</h1>



<div class="row">
  <div class="col-sm-10">
    <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item">
          <a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">
            投稿一覧  
            <span class="badge badge-secondary">
              <%= @user.posts.count %>
            </span>
          </a>
        </li>
     
        <li class="nav-item">
          <a href="<%= likes_user_path(@user) %>" class="nav-link active">
            お気に入り
            <span class="badge badge-secondary">
              <%= @user.favorites.count %>
            </span>
          </a>
        </li>
    </ul>
  </div>
  <%= render 'posts/posts', posts: @posts %>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>さんの詳細ページ</h1>



<div class="row">

  <div class="col-sm-10">
    <ul class="nav nav-tabs nav-justified mb-3">
      
        <li class="nav-item">
          <a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">
            投稿一覧  
            <span class="badge badge-secondary">
              <%= @user.posts.count %>
            </span>
          </a>
        </li>
     
        <li class="nav-item">
          <a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(favorites_user_path(@user)) %>">
            お気に入り
            <span class="badge badge-secondary">
              <%= @user.favorites.count %>
            </span>
          </a>
        </li>
    </ul>
  </div>
  <%= render 'posts/posts', posts: @posts %>
  <div class="col-sm-2">
  </div>
</div>