config/routes.rb
Rails.application.routes.draw do
  
  root "posts#index"
  resources :posts do
    member do
      post :tags
      delete :tag_d
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  
  post "favorites", to: "favorites#create"
  delete "favorites", to: "favorites#destroy"
  
  post "favorites_show", to: "favorites#create_show"
  delete "favorites_show", to: "favorites#destroy_show"
  resources :tags , only:[:show] do
    member do
      get :find
    end
  end
  resources :users, only:[:index, :show, :new, :create] do
    member do
      get :likes
      get :favorites
    end
  end
  
  resources :favorites, only: [:create, :destroy]#お気に入り登録/解除
  
end

app/models/post.rb
class Post < ApplicationRecord
  
      validates :image, presence: true
      validates :title, presence: true, length: { maximum:10 }
      validates :comment, presence: true, length: { maximum:50 }
      
      mount_uploader :image, ImageUploader
      
      belongs_to :user
      
      has_many :post_tags,dependent: :destroy
      has_many :tags, through: :post_tags, source: :tag
      
      has_many :favorites,dependent: :destroy

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  PER = 9
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page(params[:page]).per(PER)
    @tag = Tag.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @tag = Tag.new
  end

  # GET /posts/new
  def new
    if logged_in?
      @post = Post.new
      @name1　= ""
      @name2  = ""
      @name3  = ""
    else
      redirect_to login_path
    end
  end

  # GET /posts/1/edit
  def edit
    if @post.user.id == current_user.id
    else
      redirect_to root_path
    end
  end


  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @namearray = [tag1_params,tag2_params,tag3_params]
    @newarray = []
      @namearray.each do |name|
        unless name == nil
            @tag = Tag.new(name: name)
            @newarray.push(@tag)
        end
      end

    
    ActiveRecord::Base.transaction do
      @post.save!
                @newarray.each do |tag|
                    @check = Tag.find_by(name: tag.name)
                    @new_post = Post.find_by(title: @post.title)
                      unless @check
                            if tag.save!
                              @new_tag = Tag.find_by(name: tag.name)
                              @new_post.post_tags.find_or_create_by(tag_id: @new_tag.id)
                            end
                      else
                        @new_post.post_tags.find_or_create_by(tag_id: @check.id)
                      end
                end
    if @newarray.length ==0
      a = Tag.new(name: nil)
      a.save!
    end 
      flash[:success] = '投稿に成功しました。'
    end
      redirect_to @post
    rescue => e
      flash.now[:danger] = '投稿に失敗しました。'
      puts e.message
      @name1 =  tag1_params
      @name2  = tag2_params
      @name3  = tag3_params
      if @name1 == nil && @name2 == nil && @name3 == nil
        @em = "タグを1つ以上入力してください。"
      end 
      render :new
      #redirect_to new_post_path
  end


  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.user.id == current_user.id
      respond_to do |format|
        if @post.update(post_params)
          flash[:success] = '投稿を更新しました。'
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        else
          flash[:danger] = '投稿に失敗しました。'
          format.html { render :edit }
        end
      end
    else
      redirect_to root_path
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if @post.user.id == current_user.id
    @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url }
        #format.json { head :no_content }
        flash[:success] = '投稿を削除しました。'
      end
    else
      redirect_to root_path
    end
  end
  
  def tags
    @post = Post.find(params[:id])
    @tag = Tag.new(tag_params)
    @check01 = Tag.where(name: @tag[:name])#配列
        if count_tags(@post) > 4
          flash[:danger] = 'タグの追加に失敗しました。'
          render :show
          return
        end
    unless @tag.name == nil || @tag.name == ""
      if @check01.length == 1
        @post.post_tags.find_or_create_by(tag_id: @check01.first.id)
        flash[:success] = 'タグの追加に成功しました。'
        redirect_to post_path
      else
          if@tag.save
            @new_tag = Tag.find_by(name: @tag.name)
            @post.post_tags.find_or_create_by(tag_id: @new_tag.id)
            flash[:success] = 'タグの追加に成功しました。'
            redirect_to post_path
          else
            flash[:danger] = 'タグの追加に失敗しました。'
            render :show
            return
          end
      end
    else
      flash[:danger] = 'タグの追加に失敗しました。'
      render :show
      return
    end
  end

  def tag_d
      @post = Post.find(params[:id])
      if @post.tags.count > 1
      @p_t = PostTag.find_by(post_id: params[:id],tag_id: params[:tag_id])
      @p_t.destroy
      flash[:success] = 'タグの削除に成功しました。'
      else

      end
      redirect_to post_path(params[:id])
      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post)
            .permit(
              :user_id,
              :image,
              :title,
              :comment,)
    end
    
    def tag1_params
        unless params[:name1] == ""
          params.require(:name1)
        end
    end
    
    def tag2_params
        unless params[:name2] == ""
          params.require(:name2)
        end
    end
    
    def tag3_params
        unless params[:name3] == ""
          params.require(:name3)
        end
    end
    
    def tag_params
        params.require(:tag).permit(:name)
    end 
    
    def dtag_params
      params.require(:tag_id)
    end 
end

app/helpers/posts_helper.rb
module PostsHelper
    def add_tag(other_post)

    end 
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>

<%= render 'layouts/messages', model: form.object %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <div class="form-group row">
      <%= form.label :image,"画像:",class:"col-sm-2" %>
    <div class="col-sm-10">
        <%= form.file_field :image,class:"form-control-file"%>
    </div>
    </div>
  
    <div class="form-group row">
        <%= form.label :title, 'タイトル：',class:"col-sm-2" %>
    <div class="col-sm-10">
        <%= form.text_field :title, class: 'form-control' %>
    </div>
    </div>

    <div class="form-group row">
        <%= form.label :comment, 'コメント：',class:"col-sm-2" %>
    <div class="col-sm-10">
        <%= form.text_field :comment, class: 'form-control' %>
    </div>
    </div>
    
        <div class="form-group row">
                <%= form.label :name1, 'タグ1：',class:"col-sm-2" %>
        <div class="col-sm-2">
                  <%= text_field_tag :name1 ,name1, class: 'form-control'%>
        </div>
        </div>
        
        <div class="form-group row">
                <%= form.label :name2, 'タグ2：',class:"col-sm-2" %>
        <div class="col-sm-2">
                  <%= text_field_tag :name2 ,name2, class: 'form-control'%>
        </div>
        </div>
          
        <div class="form-group row">
            <%= form.label :name3, 'タグ3：',class:"col-sm-2" %>
        <div class="col-sm-2">
                  <%= text_field_tag :name3 ,name3, class: 'form-control'%>
        </div>
        </div>
        
    <div class="actions col-sm-2">
      <%= form.submit "投稿",class:"btn btn-primary"%>
    </div>

  <% end %>

app/views/posts/_posts.html.erb
<% @posts.order(id: :desc).each do |post| %>
      <div class="card" style="width: 22rem;">
        <%= image_tag post.image.url,class:"card-img-top image",alt:"Card image cap"%>
            <div class="card-header">
              <h5 class="card-title card-post">
                <%= link_to post.title, post %>
              </h5>
              <% unless current_user == nil %>
                    <% if current_user.fav_now(post) #お気に入り解除%>
                        <%= form_with(model: current_user.favorites.find_by(post_id: post.id), local: true, method: :delete) do |f| %>
                          <% #hidden_field_tag :post_id, post.id %>
                          <%= link_to(favorites_path(post_id: post.id), method: :delete) do %>
                            <i class="fas fa-star fav-icon"></i>
                          <% end %>
                        <% end %>
                    <% else#お気に入り %>
                        <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
                           <% #hidden_field_tag :post_id, post.id %>
                            <%= link_to(favorites_path(post_id: post.id), method: :post) do %>
                            <i class="far fa-star fav-icon"></i>
                            <% end %>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
            <div class="card-body">
              <div class="card-text card-post">
                <div>投稿者:<%= link_to User.find(post.user_id).name,user_path(post.user) %></div>
                <%= post.comment %>
              </div>
            </div>
          <% #タグの数だけループさせる %>
          <div class="card-footer card-post">
            <% post.tags.each do |tag| %>
                  <%= link_to tag.name,find_tag_path(tag) ,class: "btn btn-primary tag-btn"%>
            <% end %>
          </div>

        </div>  
    <% end %>

app/views/posts/edit.html.erb
<h1>投稿編集ページ</h1>

<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <%= form.hidden_field :user_id, value: current_user.id %>
    
  
    <div class="form-group row">
            <%= form.label :title, 'タイトル：',class:"col-sm-2" %>
        <div class="col-sm-10">
            <%= form.text_field :title, class: 'form-control' %>
        </div>
    </div>

    <div class="form-group row">
            <%= form.label :comment, 'コメント：',class:"col-sm-2" %>
        <div class="col-sm-10">
            <%= form.text_field :comment, class: 'form-control' %>
        </div>
    </div>
        
    <div class="actions col-sm-4">
      <%= form.submit "変更を確定",class:"btn btn-primary"%>
      <%= link_to '戻る', posts_path,class:"btn btn-primary" %>
<%= link_to '投稿を削除', @post, method: :delete, data: { confirm: '本当に削除しますか?' },class:"btn btn-danger" %>
    </div>

  <% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<div  class="border border-primary">
  <h5>
    利用方法
  </h5>
  <p>PCデスクの写真を投稿、シェア出来るWebアプリです。</p>
  <p>投稿はログイン後行う事が出来ます。</p>
  <p>タグをクリックする事で同じタグが登録されている投稿のみを表示出来ます。</p>
  <p>タグは1つ以上5個以下付けることが出来、ログインすれば誰でも編集可能になります。</p>
</div>
<div class="row">
    <%= render 'posts/posts', posts: @posts %>
</div>
<div class="row">
    <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div>
<h1>新規投稿</h1>

<div  class="border border-primary">
  <h5>
    投稿方法
  </h5>
  <p>タイトルは10文字以内で投稿して下さい。</p>
  <p>タグは3つまで同時に追加できます。タグは投稿後に編集可能です。</p>
  <p>タグは一つ以上追加してください。</p>
</div>

<%= render 'form', post: @post, name1: @name1, name2: @name2, name3: @name3%>

</div>

app/views/posts/show.html.erb
<div class="row" id="post-show">
    <div class="col-sm-8">
        <div>
          <%= image_tag @post.image.url,class:"card-img-top",alt:"Card image cap"%>
        </div>
        <% if current_user == @post.user %>
          <% post = @post%>
          <%= link_to 'Edit', edit_post_path(@post) %>
          
        <% end %>
    </div>
    <div class="col-sm-4">
          <div class="border border-primary show_field">
            
            投稿者:<%= link_to User.find(@post.user_id).name,user_path(@post.user_id) %>
            <br>タイトル:<%= @post.title %>
          </div>
          
          <div class="border border-primary show_field">
            <%= @post.comment %>
          </div>
          
        <div class="border border-primary show_field">
         <% #タグの数だけループさせる %>
            <% @post.tags.each do |tag| %>
              <div class="tag-box">
                    <%= link_to tag.name,find_tag_path(tag) ,class: "btn btn-primary btn-sm tag-btn-s"%>
                  <% if @post.tags.length > 1 && logged_in? %>
                    <%= link_to '×', tag_d_post_path(@post.id,tag_id: tag.id), method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger btn-sm tag-btn-d" %>
                  <% end %>
              </div>
            <% end %>
        </div>
        <% if logged_in? && @post.tags.count < 5 %>
          <div class="border border-primary show_field">
            <h5>タグ追加</h5>
            <%= form_with(model: @tag, url: tags_post_path , method: :post) do |form| %>
              <div class="field">
                  <%= form.label :name,"タグ名" %>
                  <%= form.text_field :name ,:placeholder => "10文字以内" %>
                  <%= form.submit  "タグを追加する",class: "btn btn-primary btn-sm" %>
              </div>
            <% end %>
          </div>
        <% end %>
          <% unless current_user == nil %>
            <div class="border border-primary show_field">
                   <% if current_user.fav_now(@post) #お気に入り解除%>
                        <%= form_with(model: current_user.favorites.find_by(post_id: @post.id), local: true, method: :delete) do |f| %>
                          <% #hidden_field_tag :post_id, post.id %>
                          <%= link_to(favorites_show_path(post_id: @post.id), method: :delete) do %>
                            <i class="fas fa-star"></i>お気に入り解除
                          <% end %>
                        <% end %>
                    <% else#お気に入り %>
                        <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
                           <% #hidden_field_tag :post_id, post.id %>
                            <%= link_to(favorites_show_path(post_id: @post.id), method: :post) do %>
                            <i class="far fa-star"></i>お気に入り登録
                            <% end %>
                          <% end %>
                    <% end %>
            </div>
          <% end %>
          
    </div>
</div>