config/routes.rb
Rails.application.routes.draw do
  
  root "posts#index"
  resources :posts do
    member do
      post :tags
      delete :tag_d
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  
  post "favorites", to: "favorites#create"
  delete "favorites", to: "favorites#destroy"
  
  post "favorites_show", to: "favorites#create_show"
  delete "favorites_show", to: "favorites#destroy_show"
  resources :tags , only:[:show] do
    member do
      get :find
    end
  end
  resources :users, only:[:index, :show, :new, :create] do
    member do
      get :likes
      get :favorites
    end
  end
  
  resources :favorites, only: [:create, :destroy]#お気に入り登録/解除
  
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning ">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      <% unless @em == nil%>
        <li><%= @em %></li>
      <% end %>
    </ul>
  </div>
<% else %>
  <% unless @em == nil%>
    <div class="alert alert-warning ">
      <ul>
          <li><%= @em %></li>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<div>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">SETUPSHOW</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in?%>
          <li class="nav-item"><%= link_to '投稿',new_post_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログアウト',logout_path, method: :delete, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'マイページ',user_path(current_user), class: 'nav-link' %></li>
         <% else %>
          <li class="nav-item"><%= link_to 'ユーザー登録',new_user_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login',login_path, class: 'nav-link' %></li>
         <% end %>
          
      </ul>
    </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SETUPSHOW</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    
    <style>
    p{line-height:4px;}
    .card{margin:10px;}
    .card-header{padding:10px;}
    .card-body{padding-top:10px;}
    .card-footer{padding:5px;}
    .message{margin-top:0px;}
    .card-post{margin-bottom:0px;
              float:left;}
    .tag_icon{margin-bottom:0px;
              padding:2px;}
    .show_post{width:100%;
               height:100%;}
    .show_field{padding:10px;
                margin:15px;}
    .fav{float:right;}
    .tag-btn{margin-bottom:5px;}
    .tag-box{margin-bottom:5px;}
    .tag-btn-s{width:80%;}
    .tag-btn-d{}
    #post-show{margin-top:50px;}
    .fav-icon{float: right;}
    .image{max-height:200px;
           object-fit: contain;}
    </style>

  </head>

  <body>

    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash_messages' %>
<div class="container">
<% if logged_in?%>
<div class="row">
    Hello,<%= current_user.name %> !!
</div>
<% end %>

      <%= yield %>
    </div>
  </body>
</html>